dist: trusty
sudo: false
branches:
  only:
    - master
    - staging
language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install lxml
script:
  - pytest