dist: trusty
sudo: false
branches:
  only:
    - staging
language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "python setup.py install"
install:
  - pip install -r requirements.txt
script:
  - pytest